# 简单夹爪控制器配置示例
# 用于ros2_control的控制器管理器配置

controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    # 简单夹爪控制器
    hand_controller:
      type: adaptive_gripper_controller/AdaptiveGripperController

    # 关节状态广播器
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster


# 简单夹爪控制器参数配置
hand_controller:
  ros__parameters:
    # 基本夹爪参数
    joint: "gripper_joint"
    # 力反馈阈值参数
    force_threshold: 0.1  # 力阈值（牛顿），超过此值将停止夹取


# 关节状态广播器配置
joint_state_broadcaster:
  ros__parameters:
    joints:
      - gripper_joint
