controller_manager:
  ros__parameters:
    update_rate: 100  # Hz
    
    my_robot_controller:
      type: unitree_g1_controller/MyRobotController

    # Required joint state broadcaster
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

my_robot_controller:
  ros__parameters:
    joints:
      - left_hip_pitch_joint
      - left_knee_joint
      - left_ankle_pitch_joint
      - right_hip_pitch_joint
      - right_knee_joint
      - right_ankle_pitch_joint
      - waist_pitch_joint
      - waist_roll_joint
    effort: 5.0  # Default effort value in Nm

# 硬件配置
hardware:
  ros__parameters:
    type: unitree_ros2_control/HardwareUnitree
    robot_type: "humanoid"
    domain: 1
    network_interface: "lo"
    show_foot_force: false  # G1没有足力传感器
    enable_high_state: false

# 使用模拟硬件进行测试
# hardware:
#   ros__parameters:
#     type: mock_components/GenericSystem
#     mock_sensor_commands: true
#     state_following_offset: 0.0
#     joints:
#       - left_hip_pitch_joint
#       - left_knee_joint
#       - left_ankle_pitch_joint
#       - right_hip_pitch_joint
#       - right_knee_joint
#       - right_ankle_pitch_joint
#       - waist_pitch_joint
#       - waist_roll_joint
#     command_interfaces:
#       - effort
#     state_interfaces:
#       - position
#       - velocity
#       - effort