controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    imu_sensor_broadcaster:
      type: imu_sensor_broadcaster/ImuSensorBroadcaster

    # 为Go2机器人添加更多控制器
    joint_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController

hardware_unitree_sdk2:
  ros__parameters:
    # Go2机器人配置
    robot_type: "quadruped"  # 指定机器人类型为四足机器人
    domain: 1
    network_interface: "lo"
    show_foot_force: true  # Go2有足力传感器
    enable_high_state: true  # 仿真环境启用高状态，真实机器人设为false
