controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    imu_sensor_broadcaster:
      type: imu_sensor_broadcaster/ImuSensorBroadcaster

    # 为Go2机器人添加更多控制器
    joint_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController

hardware_unitree_sdk2:
  ros__parameters:
    # 真实Go2机器人配置
    robot_type: "quadruped"  # 指定机器人类型为四足机器人
    domain: 1
    network_interface: "eth0"  # 真实机器人使用以太网接口
    show_foot_force: true  # Go2有足力传感器
    enable_high_state: false  # 真实机器人禁用高状态
